### ISSUE TITLE
Add smhasher and Yves's smhasher results to asses hash quality

### ISSUE THREAD

**Issue by dumblob** [ktprime/ktprime#3]
To assess hash quality, would you consider running the following "state of the art" hash tests?

1. https://github.com/rurban/smhasher

2. stricter (better) counterpart/fork of smhasher (but less actively maintained): https://github.com/demerphq/smhasher/ as described in https://github.com/rurban/smhasher/issues/31

**Comment by ktprime** [comment]
I do not know how to add my hash to the test case,  can you help me.

**Comment by dumblob** [comment]
First please extract all hash functions which are not yet present in smhasher and then submit a pull request in the smhasher repository.

If I'm not mistaken, the only hash function not already present in smhasher is the *"Thomas Wang's function"* (line 1489 in `hash_table6.hpp`)...

**Comment by ktprime** [comment]
your are right,  I need a very good(both efficient and good distribution statistics) hash function in my hash table if the default hash function is not so good(highly collison).  my later hash table will use a default(current is Thomas Wang's function)  hash function during rehash or insert  if user's input hash is not good. I need more time to test.

smhasher is very good and detail  for many different hash function performance, thanks for your help
and I will test smhasher and it may help my hash table.

if your are interest in c++ hash map,  my hash table is very efficient from the benchmark  https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
:) and my code need a readme and how to use and about it's design, more test case ...

**Comment by dumblob** [comment]
>if your are interest in c++ hash map, my hash table is very efficient from the benchmark https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
:) and my code need a readme and how to use and about it's design, more test case ...

Yeah, it seems good. There is though a major downside (actually a complete show stopper), which is the license - I can only recommend to relicense everything under zlib or MIT license without any additional (commercial) restrictions. That's also the reason why I can't use the hash map currently :cry:.

**Comment by ktprime** [comment]
> > if your are interest in c++ hash map, my hash table is very efficient from the benchmark https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
> > :) and my code need a readme and how to use and about it's design, more test case ...
> 
> Yeah, it seems good. There is though a major downside (actually a complete show stopper), which is the license - I can only recommend to relicense everything under zlib or MIT license without any additional (commercial) restrictions. That's also the reason why I can't use the hash map currently 😢.

  I have update the license to MIT license now,  hash_table5.hpp is very stable without many features and
fully tested by me. if you want to use  or benchmark, just use this one.

hash_table6.hpp is newer version and under developing.
main features as fllow:
0. the main bucket/slot is core ideal, use only one array to save data.
1. combine 3 different linear/quadratic/random probing ways
2. linked collsion slot like separate chaining, it's the most fastest find performance(special for hot cache)
3. specially optimization with cpu cache line size
4. a very newly and fast rehash algorithm
5. can set a high load factor(0.99, 10% performance lost)
6. lru get/set by set compile marco
7. change a default hash function during rehash if the input's hash function is not good or high collisions(average slot size is more than 4)
8. if the key and value's size is different, it can save more memory than other open addressing hash map implemention (ex key = int64, value = int)
9. with c++ pod data, it's clear/copy is efficent by using memcpy

some bad:
1. iterator performance is normal, very bad if the load_factor is very low(call shrink_to_fit by hand)
2. clear sometimes is not cache good
3. key = string performance is not highly optimization

**Comment by dumblob** [comment]
>I have update the license to MIT license now

Wow, thanks a lot!

>key = string performance is not highly optimization

According to your description (I didn't run any tests so far) this could be a bottle neck for "everyday use" of the hash map. But keep the good work and there'll be a way to improve it sooner or later.

**Comment by ktprime** [comment]
optimization key = string is some difficulty because calculation of string's hash key very slow, and string compartion/copy/new is also slow(some dynamic memory alloc/free) .  
one optimization way is cache string hash value can improve a little.

This guy have some special string hash map.  https://github.com/Tessil
