### ISSUE TITLE
rehash public

### ISSUE THREAD

**Issue by jamespmonaco** [ktprime/ktprime#5]
For the hashmaps, should rehash be public?  This seems to be the standard with most the other hashmaps. I see one has shrink_to_fit which calls rehash (but the other does not).  

This is a great hashmap!  I've been comparing it to many others, and it has clearly been the best.

**Comment by ktprime** [comment]
rehash is very slow, using reserver instead of  rehash. I'll set rehash to be public soon.
if the hash map 's load factor is small(after many erase), shrink_to_fit is good choise for saving memory if necessary.
  
I add some non-standard function for performance issiue, for example insert_unique and _erase.

**Comment by jamespmonaco** [comment]
OK, thanks for the help!  Could you tell me the difference between the hashmap in emillib2 (hash_table5.hpp) and the one in emillib3 (hash_table6.hpp)?  Both seem to be getting updated.  Thanks!

**Comment by ktprime** [comment]
hash_table6.hpp have some new feature , it's find performance (key is interger type, hit 100% ) is 7% fast than hash_table5.hpp. but find miss performance is a lillte slow than emillib2.

emillib3's load factor can set to be 1.0  if the compile macro flag is set EMILIB_HIGH_LOAD for saving memory.  but the  average performane loss 5-10%

my  benchmark (k,v = long, long, 3574 test case) with other hash map as follow. the thrid cloumn score is performane ration. score 100 is mean best.  if you need I can upload my test code.

reinsert after ease 50%
   26206        emilib2                 100
   26501        phmap flat              98
   26894        emilib3                 97
   27232        skarupk flat            96
   28569        martin flat             91
   45894        tessil robin            57

find_erase after erase 50%
   3380         martin flat             100
   4516         phmap flat              74
   4750         emilib2                 71
   5066         emilib3                 66
   5636         skarupk flat            59
   5964         tessil robin            56

find_half 50%
   3974         phmap flat              100
   4642         martin flat             85
   4842         emilib2                 82
   5029         emilib3                 79
   7477         skarupk flat            53
   9024         tessil robin            44

find_hit 100%
   5426         emilib3                 100
   5777         emilib2                 93
   6457         phmap flat              84
   7801         skarupk flat            69
   8492         martin flat             63
   9793         tessil robin            55

find_miss 0%
   5392         phmap flat              100
   5994         martin flat             89
   6366         emilib2                 84
   6417         emilib3                 84
   10200        tessil robin            52
   10307        skarupk flat            52

hash_erase  erase 50%
   8264         martin flat             100
   8814         phmap flat              93
   8898         emilib2                 92
   10270        emilib3                 80
   11457        tessil robin            72
   14776        skarupk flat            55

hash_insert insert no reserve
   27760        phmap flat              100
   29815        emilib2                 93
   30763        emilib3                 90
   32153        skarupk flat            86
   33438        martin flat             83
   40716        tessil robin            68

hash_insert insert with reserve
   11046        emilib3                 100
   11295        emilib2                 97
   19530        skarupk flat            56
   19714        phmap flat              56
   20105        tessil robin            54
   32868        martin flat             33

============== map rank ==================
      emilib2   96
      emilib3   94
  martin flat   73
   phmap flat   92
 skarupk flat   76
 tessil robin   62

//cpu info
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb00001d
cpu MHz         : 2299.822
cache size      : 20480 KB
physical id     : 1

**Comment by jamespmonaco** [comment]
Thanks.  That helps a lot.  I get slightly different results for the insert.  I'll put the graphs here in case you're interested.  It would be nice to know what causes the increased cost for small numbers of inserts.

![insert_10000](https://user-images.githubusercontent.com/10563744/64070358-f1914400-cc2b-11e9-8691-b5eda7603034.jpeg)

**Comment by ktprime** [comment]
a very good job you do, you can try test finding/erasing performance with a very large size(n > 10^8).
From my test emilib is the fastest  with hot finding and inserting(with reserve) performance.
I have never test small hash performance(n < 10^5) before. 

   emilib is slower than some others  with iterator, rehash(large size) and miss finding. I'll do some more optimization now.

phmap and absl default load factor is 7/8 and emilib is 0.8(0.85 is ok). during inserting if hash map's memory size > CPU L1 cache(32kb mostly), the performance dscrease dramacity  which can be see from your test cure.

more test you can find from https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/ and https://1ykos.github.io/ordered_patch_map/

**Comment by jamespmonaco** [comment]
Thanks! I have several other tests and emilb is as good or better at each.  I'm redoing them now and will share the results.

**Comment by ktprime** [comment]
if your test case use hash_map<long,int> instead of hash_map<long,long>, emilib can save 1/3 memory
use and performance can improved 20% up at least.

from my test I think this guy's https://github.com/martinus/robin-hood-hashing is the most efficient hash map.

**Comment by jamespmonaco** [comment]
That's close to my test case hash_map<unsigned long long, short int>.

**Comment by ktprime** [comment]
Bencmark result is depended on many factors, compiler(clang, gcc, msvc), OS(linux, windows, mac), cpu(amd. intel. arm64), memory(ddr3, ddr4) test case(find, insert, erase, iterator, copy) and work load.  it's very diffculty to say one hash map is good or worse than others if not do a fully test and compare.

**Comment by jamespmonaco** [comment]
Yes, that seems to be exactly correct.  That is why I'm testing it for our exact situation.  The available benchmarks are nice, but may not be ideal for our situation.

**Comment by jamespmonaco** [comment]
These are the find times I get.  Again, for my case anyway, the emillib does as well as any of the others. (And, of course, much better with the inserts.)

![find_buckets](https://user-images.githubusercontent.com/10563744/64071016-99b00880-cc3e-11e9-92f7-bcc7efcc6526.png)
![find_time](https://user-images.githubusercontent.com/10563744/64071019-a3397080-cc3e-11e9-91c6-5c77ee9f9116.png)

**Comment by ktprime** [comment]
quite interesting and amazing test result.
emilib focus on finding optimaztion with dataset size > cpu cache size and less cache line miss. if the dataset is small which can be filled into cpu cache so latency is not a key factor which can be shown all others hash map is also good or better. 
std::unordered_map is slowest because much cache line miss because it use dynamic alloc(maybe random memory).

**Comment by jamespmonaco** [comment]
This is another interesting experiment: It inserts and deletes 1M elements in the hashmap.  The inserts and deletes (at each step) are drawn from a uniform distribution between 0 and 100.  However, we can obviously never delete more elements than are in the hashmap at the current step.  This leads to the hashmap growing until all the elements are added, and then shrinking back to empty.  This total simulation is run 5000 times. Emilib again does very well.

Reserve of 16000

Mean maximimum number of elements ever in hashmap: 7268.65+-2884.94

STD
Time: 0.0715712 +- 0.00995836
Buckets: 16545.5+-1497.68

EMIL3
Time: 0.0123522 +- 0.00331154
Buckets: 17147.5+-3453.43

EMIL2
Time: 0.0116155 +- 0.00324158
Buckets: 17147.5+-3453.43

Abseil
Time: 0.0229678 +- 0.0024344
Buckets: 21393.2+-8397.28

Ska_Flat
Time: 0.0175413 +- 0.00274854
Buckets: 21859.5+-8521.42

Ska_Bytell
Time: 0.0210909 +- 0.00390603
Buckets: 16659.3+-2105.7

PhMap
Time: 0.0218437 +- 0.00217841
Buckets: 21383.4+-8374.34

TSL_RH
Time: 0.0154569 +- 0.00303093
Buckets: 21859.5+-8521.42

Reserve of 1000

Mean maximimum number of elements ever in hashmap: 7268.65+-2884.94

STD
Time: 0.0769681 +- 0.0096534
Buckets: 10634.3+-4738.03

EMIL3
Time: 0.0160397 +- 0.00319564
Buckets: 13234.2+-5971.79

EMIL2
Time: 0.0152505 +- 0.00312541
Buckets: 13234.2+-5971.79

Abseil
Time: 0.0247667 +- 0.00236812
Buckets: 20295.5+-9428.63

Ska_Flat
Time: 0.0180499 +- 0.00284271
Buckets: 21127.2+-9283.23

Ska_Bytell
Time: 0.0266675 +- 0.00480111
Buckets: 11307.4+-5078.52

PhMap
Time: 0.0235317 +- 0.00220918
Buckets: 20309.4+-9387.34

TSL_RH
Time: 0.0162163 +- 0.00302612
Buckets: 21123.9+-9282.02

**Comment by jamespmonaco** [comment]
If my reading of your code is correct, you're using the hash from the standard library.  Have you ever tried Fibonacci Hashing?  I'm still new to hash maps, but this seems like something beneficial.  Thanks!

**Comment by ktprime** [comment]
compiler my code with flag  EMILIB_FIBONACCI_HASH can use Fibonacci Hashing. it's a very great and safe hashing but sometimes slower if the dataset is not so bad . I've improved erase performance  just now.

**Comment by jamespmonaco** [comment]
Interesting, thanks!  I'll grab your new code soon and see how it effects my specific tests.

**Comment by jamespmonaco** [comment]
Another interesting thing I just noticed, your HashSet inserts at the same speed as a contiguous vector even at only five unique inserts!  Much, much faster than Google's or any others.

**Comment by ktprime** [comment]
HashSet is very fast for small key( average 30-50% comprared with vector), But it's not so efficient with big key compraed with node-base hash map beacuse much more cache miss and move/copy opertion during insert, earse or rehash. I'll develop a node-base hash map in future. 
In fact I have many new ideal on how to optimizate performance.

**Comment by ktprime** [comment]
HashSet is very fast for small key( average 30-50% comprared with vector), But it's not so efficient with big key compared with node-base hash map beacuse much more cache miss and move/copy operation during insert, earse or rehash. I'll develop a node-base hash map in future. 
In fact I have many new ideals on how to optimizate performance.

**Comment by ktprime** [comment]
HashSet is very fast for small key( average 30-50% comprared with vector), But it's not so efficient with big key compared with node-base hash map beacuse much more cache miss and move/copy operation during insert, earse or rehash. I'll develop a node-base hash map in future. In fact I have many new ideals on how to optimizate performance.

**Comment by ktprime** [comment]
{
       n = 12345678;
        std::vector <int> data(n);
        for (int i = 0; i < n; i ++)
            data[i] = i;

        myrandom_shuffle(data.begin(), data.end());

        {
            auto ts = now2ms();
            emilib2::HashMap<int, int> emap(n);
            for (auto v: data)
                emap.insert(v, 0);
            printf("emap insert time = %ld ms\n", now2ms() - ts);
        }

        {
            auto ts = now2ms();
            emilib2::HashMap<int, int> emap(n);
            for (auto v: data)
                emap.insert_unique(v, 0);
            printf("emap unique time = %ld ms\n", now2ms() - ts);
        }

        {
            auto ts = now2ms();
            std::unordered_map<int, int> umap(n);
            for (auto v: data)
                umap.emplace(v, 0);
            printf("umap insert time = %ld ms loadf = %.3lf\n", now2ms() - ts, umap.load_factor());
        }

        {
            auto ts = now2ms();
            std::vector<int> v(n);
            for (auto d: data)
                v[d] = 0;
            printf("vec    time = %ld ms\n", now2ms() - ts);
        }

        {
            auto ts = now2ms();
            emilib9::HashSet<int> eset(n);
            for (auto v: data)
                eset.insert_unique(v);
            printf("eset unique time = %ld ms\n", now2ms() - ts);
        }

        {
            auto ts = now2ms();
            std::unordered_set<int> eset(n);
            for (auto v: data)
                eset.insert(v);
            printf("uset insert time = %ld ms\n", now2ms() - ts);
        }
        puts("\n");
    }


emap insert time = 432 ms
emap unique time = 312 ms
umap insert time = 1620 ms loadf = 0.942
vec    time = 296 ms
eset unique time = 224 ms
uset insert time = 1760 ms

**Comment by jamespmonaco** [comment]
Very nice. Thanks

Just a quick question: the hashmap and hashset are always in contiguous memory, correct?  There is no chaining or anything like that.

**Comment by ktprime** [comment]
yes. it's often called flat hash map. do you benchmark it just for fun or use in future?
I use a contiguous array to simpulate a chain but most other's implemention use two arrays(one for k.v and other for index).

**Comment by jamespmonaco** [comment]
Thanks, I just wanted to confirm. Until three months ago I worked in medical imaging developing computer vision and machine learning algorithms, mostly in Matlab (so my C++ is very rusty).  I just joined a friend who has been doing automated high-speed trading.  It's a very interesting field from both computer science and mathematical modelling perspectives. We have been looking for a quick method for accessing tables and sets. For what we need, the emilib seems to be the all around best (both in terms of access times and memory usage) by quite a large margin.  You've done a great job. My next step will be to test all the boundary conditions etc... before we integrate it into the existing system. 

I'm happy to share anything I discover if it could potentially help you.

**Comment by jamespmonaco** [comment]
Are you developing these for fun, or is this part of a research project?

**Comment by ktprime** [comment]
both, it is used in my job and I pay some spare time  to optimizate performance.  I'm lazy not support any doc, test , benchmark  to user :(. before it's integrated into your projcet, a fully test is very
necessary. I benchmark and test it very day and compare with other's hash if any tiny change from my new ideal. If you just care about finding performance with small key-value this one is a very good choice. my core algorithm is quite different from the others(robin hood hashing) which is used by  many hash map(tsl, phmap, ska, martin ...).

**Comment by ktprime** [comment]
I have a new hash_table7.hpp. it's fast than emilib2 for find miss, erase or big key-value (ex key = string).

**Comment by jamespmonaco** [comment]
Great, thanks for letting me know!

**Comment by ktprime** [comment]
some new hash map  is created on a new repository  https://github.com/ktprime/emhash
I have add the README.md and some bench.

**Comment by ktprime** [comment]
I have a new hash_map https://github.com/ktprime/emhash/blob/master/hash_table7.hpp, it's default load factor is 0.9 which is a very high factor for flat hash map(absl is 7/8 = 0.875). 

From my benchmark it's fastest hash map for inserting if default load factor > 0.8.  I have design a very good and cache friendly algorihm for fast finding empty bucket base on cpu bitscanf instruction(x86).
  
  Facebook's f14 and google's absl(sse2 instruction) hash map can find 14 empty slots once and my implemention can search 64 bucket.

**Comment by jamespmonaco** [comment]
Great, thanks!

**Comment by ktprime** [comment]
The default load factor is 0.95 now and even can set to 0.998 if you cant to save memory in https://github.com/ktprime/emhash/blob/master/hash_table7.hpp.
it's performacne is some tiny improved and fix some issuse.

**Comment by jamespmonaco** [comment]
Great, thanks!
